

#spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant
#spring.datasource.username=user
#spring.datasource.password=pass
#spring.datasource.driver=org.postgresql.Driver


#spring.jpa.properties.hibernate.hbm2ddl.auto = create
#spring.jpa.properties.hibernate.show_sql = true


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
    enabled: true
    default-schema: public
